spring.datasource.url=jdbc:postgresql://localhost:5432/rental_management
spring.datasource.username=postgres
spring.datasource.password=root234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.secret=change-this-to-a-long-random-secret-key-for-development
jwt.expiration=3600000
