package com.example.rental_management.document.service;

import com.example.rental_management.auth.security.SecurityUtil;
import com.example.rental_management.billing.exception.BillingAccessDeniedException;
import com.example.rental_management.billing.exception.ResourceNotFoundException;
import com.example.rental_management.lease.entity.Lease;
import com.example.rental_management.lease.repository.LeaseRepository;
import com.example.rental_management.property.repository.PropertyManagerRepository;
import com.example.rental_management.user.entity.Role;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;

/**
 * Generates PDF lease documents.
 *
 * Authorization mirrors the lease read rules:
 *   TENANT           — own lease only
 *   OWNER            — leases for properties they own
 *   MANAGER          — leases for properties assigned to them
 *   MAINTENANCE_STAFF — denied
 *
 * PDF generation uses Apache PDFBox 3.x.
 */
@Service
public class DocumentService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final float MARGIN      = 60f;
    private static final float PAGE_WIDTH  = PDRectangle.A4.getWidth();
    private static final float LINE_HEIGHT = 18f;

    private final LeaseRepository leaseRepository;
    private final PropertyManagerRepository propertyManagerRepository;

    public DocumentService(
            LeaseRepository leaseRepository,
            PropertyManagerRepository propertyManagerRepository) {
        this.leaseRepository = leaseRepository;
        this.propertyManagerRepository = propertyManagerRepository;
    }

    /**
     * Generate a PDF for the given lease and return its bytes.
     * Throws {@link BillingAccessDeniedException} if the caller is not authorised.
     * Throws {@link ResourceNotFoundException} if the lease does not exist.
     */
    @Transactional(readOnly = true)
    public byte[] generateLeasePdf(Long leaseId) {
        Lease lease = leaseRepository.findById(leaseId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "lease not found: " + leaseId));

        authorizeLeaseRead(lease);

        try {
            return buildPdf(lease);
        } catch (IOException e) {
            throw new IllegalStateException("failed to generate lease PDF", e);
        }
    }

    // ── Authorization ─────────────────────────────────────────────────────────

    private void authorizeLeaseRead(Lease lease) {
        Long userId = SecurityUtil.getCurrentUserId();
        Role role   = SecurityUtil.getCurrentUserRole();

        boolean allowed = switch (role) {
            case TENANT -> lease.getTenant().getId().equals(userId);
            case OWNER  -> lease.getUnit().getProperty().getOwner().getId().equals(userId);
            case MANAGER -> propertyManagerRepository
                    .findByPropertyIdAndManagerId(
                            lease.getUnit().getProperty().getId(), userId)
                    .isPresent();
            case MAINTENANCE_STAFF -> false;
        };

        if (!allowed) {
            throw new BillingAccessDeniedException(
                    "not authorised to access document for lease " + lease.getId());
        }
    }

    // ── PDF construction ──────────────────────────────────────────────────────

    private byte[] buildPdf(Lease lease) throws IOException {
        try (PDDocument doc = new PDDocument();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);

            PDType1Font bold    = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {

                float y = PDRectangle.A4.getHeight() - MARGIN;

                // ── Title ─────────────────────────────────────────────────────
                y = writeLine(cs, bold, 20, MARGIN, y, "LEASE AGREEMENT");
                y -= LINE_HEIGHT * 0.5f;
                y = writeLine(cs, regular, 10, MARGIN, y,
                        "Generated by RentFlow Rental Management System");
                y -= LINE_HEIGHT * 1.5f;

                // ── Horizontal rule ───────────────────────────────────────────
                cs.setLineWidth(0.5f);
                cs.moveTo(MARGIN, y);
                cs.lineTo(PAGE_WIDTH - MARGIN, y);
                cs.stroke();
                y -= LINE_HEIGHT * 1.5f;

                // ── Lease details ─────────────────────────────────────────────
                y = writeSection(cs, bold, regular, y, "LEASE DETAILS");

                y = writeField(cs, regular, y, "Lease ID",
                        String.valueOf(lease.getId()));
                y = writeField(cs, regular, y, "Status",
                        lease.getStatus());
                y = writeField(cs, regular, y, "Start Date",
                        lease.getStartDate().format(DATE_FMT));
                y = writeField(cs, regular, y, "End Date",
                        lease.getEndDate().format(DATE_FMT));
                y = writeField(cs, regular, y, "Monthly Rent",
                        "INR " + lease.getMonthlyRent()
                                .setScale(2, java.math.RoundingMode.HALF_UP)
                                .toPlainString());
                y -= LINE_HEIGHT;

                // ── Property & unit ───────────────────────────────────────────
                y = writeSection(cs, bold, regular, y, "PROPERTY & UNIT");

                y = writeField(cs, regular, y, "Property Name",
                        lease.getUnit().getProperty().getName());
                y = writeField(cs, regular, y, "Property Address",
                        lease.getUnit().getProperty().getAddress());
                y = writeField(cs, regular, y, "Property Type",
                        lease.getUnit().getProperty().getPropertyType());
                y = writeField(cs, regular, y, "Unit Number",
                        lease.getUnit().getUnitNumber());
                y = writeField(cs, regular, y, "Unit Type",
                        lease.getUnit().getUnitType());
                y -= LINE_HEIGHT;

                // ── Tenant & owner ────────────────────────────────────────────
                y = writeSection(cs, bold, regular, y, "PARTIES");

                y = writeField(cs, regular, y, "Tenant Name",
                        lease.getTenant().getName());
                y = writeField(cs, regular, y, "Tenant Email",
                        lease.getTenant().getEmail());
                y = writeField(cs, regular, y, "Owner Name",
                        lease.getUnit().getProperty().getOwner().getName());
                y = writeField(cs, regular, y, "Owner Email",
                        lease.getUnit().getProperty().getOwner().getEmail());
                y -= LINE_HEIGHT;

                // ── Footer ────────────────────────────────────────────────────
                float footerY = MARGIN;
                cs.setLineWidth(0.5f);
                cs.moveTo(MARGIN, footerY + LINE_HEIGHT);
                cs.lineTo(PAGE_WIDTH - MARGIN, footerY + LINE_HEIGHT);
                cs.stroke();
                writeLine(cs, regular, 9, MARGIN, footerY,
                        "This document is system-generated. Lease ID: " + lease.getId()
                        + "  |  RentFlow v1.0");
            }

            doc.save(out);
            return out.toByteArray();
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private float writeSection(PDPageContentStream cs,
                               PDType1Font bold, PDType1Font regular,
                               float y, String title) throws IOException {
        y = writeLine(cs, bold, 12, MARGIN, y, title);
        y -= LINE_HEIGHT * 0.3f;
        return y;
    }

    /**
     * Write a label : value pair. Label is 140 pts wide; value follows.
     */
    private float writeField(PDPageContentStream cs,
                             PDType1Font font,
                             float y, String label, String value) throws IOException {
        PDType1Font labelFont  = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
        PDType1Font valueFont  = font;
        float labelX = MARGIN;
        float valueX = MARGIN + 145f;

        cs.beginText();
        cs.setFont(labelFont, 10);
        cs.newLineAtOffset(labelX, y);
        cs.showText(label + ":");
        cs.endText();

        cs.beginText();
        cs.setFont(valueFont, 10);
        cs.newLineAtOffset(valueX, y);
        cs.showText(value != null ? value : "—");
        cs.endText();

        return y - LINE_HEIGHT;
    }

    private float writeLine(PDPageContentStream cs, PDType1Font font,
                            float size, float x, float y,
                            String text) throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(text);
        cs.endText();
        return y - (size + 4f);
    }
}
